@startuml Compact_SEI_ECom_CnC_v2
/' skinparam dpi 140 '/
skinparam shadowing false
skinparam defaultFontName "Arial"
skinparam ArrowColor #333
/' skinparam nodesep 40
skinparam ranksep 80 '/

title UniversalMarketPlace — C&C Services View
' System boundary
rectangle " " as SYS #eaf6e8 {
  skinparam rectangle {
    BackgroundColor #eaf6e8
    BorderColor #88b379
  }

  component "Service\nAuth\n" as AuthSvc
  component "Service\nCompte\n" as UserSvc
  component "Service\nProduit\n" as ProductSvc
  component "Service\nMise\n" as BidSvc
  component "Service\nTransaction\n" as TxSvc
  component "Service\nNotification\n" as NotifSvc

  component "Entité Utilisateur" as UserEntity
  component "Entité Produit" as ProdEntity
  component "Entité Mises" as BidEntity
  component "Entité Transaction" as OrderEntity

  /' component "Database" as dbport '/
  
  queue "Message Broker" as Broker
  
  ' Ports
  portout "Redis Cache" as RedisSvc
/'   portout " " as dbport '/
  portin " " as APIGW
  port " " as PaymentExt
}
' ---------- Connectors ----------
' Redis
RedisSvc --> Redis

' API to services
APIGW --> AuthSvc
APIGW --> UserSvc
APIGW --> ProductSvc
APIGW --> BidSvc
APIGW --> TxSvc

' Services to DB (JDBC arrows labeled)
AuthSvc -d-> UserEntity
UserSvc -d-> UserEntity
ProductSvc --> ProdEntity
BidSvc --> BidEntity
TxSvc --> OrderEntity

' Entities -> DB (explicit, like your example)
UserEntity -l-> PostgreSQL
ProdEntity -l-> PostgreSQL
BidEntity -l-> PostgreSQL
OrderEntity -l-> PostgreSQL

AuthSvc --> RedisSvc

' Broker (async notification flows)
BidSvc -[#2E8B57]-> Broker
Broker -[#2E8B57]-> NotifSvc

' Transaction flow (NO broker between Bid acceptance and TxSvc)
TxSvc -r-> PaymentExt : <<HTTPS>>
PaymentExt -r-> TxSvc
NotifSvc --> SMTP
PSP -- PaymentExt
APIGateway -- APIGW


legend right
  |=| Solid = synchronous (HTTP)
  |=| Green = asynchronous via Broker (pub/sub)
  |db| = relational DB
end legend

@enduml
